# Generated by Django 4.2.5 on 2023-10-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
